### ISSUE TITLE
Player movement speed when moving diagonally

### ISSUE THREAD

**Issue by CorbecJayne** [CorbecJayne/JoSiJaLu_2016#11]
When the player pushes two adjacent movement buttons, the Player object moves diagonally. But, because the diagonal movement works by adding tow movements together, the movement speeds are also added. This means, that the player can move diagonally faster than usual. This should be fixed by checking separately whether two movement keys are pressed at once.

**Comment by Lulalein99** [comment]
Movement speed für diagonale Richtungen ist jetzt halbiert.
Wenn zwei entgegengesetzte Knöpfe gedrückt werden, stoppt der Spieler.
