### ISSUE TITLE
Singleplayer movement

### ISSUE THREAD

**Issue by CorbecJayne** [CorbecJayne/JoSiJaLu_2016#2]
2D movement of one player through the environment (graphically displayed in a window) in all four cardinal directions and four more in-between using WASD or the arrow keys. Constant speed when holding down the button. Movement speed changeable through an attribute inside the Player Object.

- [x] Graphical display of the player object within the window

- [x] 2D movement of the player object using a keyboard switch

- [x] Cardinal movement using "WASD" or "Up/Left/Down/Right" Keyboard Keys (keybindings can later be put inside the Player Object Class)

- [x] By pressing two adjacent buttons at once, move diagonally (NE/SE/SW/NW)

- [x] Holding Down Button works, player moves at constant speed

- [x] Easy way to change the movement speed using a variable (this variable can later be an attribute within the Player Object Class)

**Comment by doej1367** [comment]
das mit der Variable ist 'ne gute Idee! Mach ich, wenn ich anfange das projekt in klassen aufzuteilen.
(dann wenn meine libGDX-tests abgeschlossen sind!)

**Comment by CorbecJayne** [comment]
Default movement speed is set to 3.

**Comment by CorbecJayne** [comment]
Issue is done, but feature was not finished in Git Flow and released.
