### ISSUE TITLE
Multiplayer movement

### ISSUE THREAD

**Issue by CorbecJayne** [CorbecJayne/JoSiJaLu_2016#4]
Simultaneous movement of two players using different key combinations (WASD and Λ<V>).
Players should be able to move in 8 directions using the four keyboard keys and four combinations of two keyboard keys.

**Comment by Lulalein99** [comment]
Wir haben nun zwei Spieler, welche sich unabhängig voneinander bewegen können.
Benutzt werden im Moment WASD und die Richtungstasten.
Beide Spieler haben die Möglichkeit sich Vertikal, Horizontal und Diagonal zu bewegen.
